document.addEventListener('DOMContentLoaded', () => {
    window.addEventListener('load', () => {const preloader = document.getElementById('preloader');if(preloader) preloader.style.opacity = '0';setTimeout(() => { if(preloader) preloader.style.display = 'none'; }, 500);});
    const navbar = document.getElementById('navbar');window.addEventListener('scroll', () => {if (window.scrollY > 50) navbar.classList.add('scrolled');else navbar.classList.remove('scrolled');});
    const themeToggle = document.getElementById('theme-toggle');const html = document.documentElement;const savedTheme = localStorage.getItem('theme') || 'dark';html.setAttribute('data-theme', savedTheme);themeToggle.querySelector('i').className = savedTheme === 'dark'? 'fas fa-sun' : 'fas fa-moon';themeToggle.addEventListener('click', () => {const currentTheme = html.getAttribute('data-theme');const newTheme = currentTheme === 'dark'? 'light' : 'dark';html.setAttribute('data-theme', newTheme);localStorage.setItem('theme', newTheme);themeToggle.querySelector('i').className = newTheme === 'dark'? 'fas fa-sun' : 'fas fa-moon';});
    const roles = ["MERN Stack Developer", "Full Stack Developer", "BCA Student"];let roleIndex = 0; let charIndex = 0; let isDeleting = false;const typingElement = document.querySelector('.typing-text');function typeEffect() {if (!typingElement) return;const currentRole = roles[roleIndex];if (isDeleting) { typingElement.textContent = currentRole.substring(0, charIndex - 1); charIndex--; }else { typingElement.textContent = currentRole.substring(0, charIndex + 1); charIndex++; }let typeSpeed = isDeleting? 100 : 150;if (!isDeleting && charIndex === currentRole.length) { typeSpeed = 2000; isDeleting = true; }else if (isDeleting && charIndex === 0) { isDeleting = false; roleIndex = (roleIndex + 1) % roles.length; typeSpeed = 500; }setTimeout(typeEffect, typeSpeed);}setTimeout(typeEffect, 1000);
    const terminalInput = document.getElementById('terminal-input');const terminalOutput = document.getElementById('terminal-output');const terminalCommands = {help: () => `Available commands:<br>&nbsp;&nbsp;<span style="color:#00d2ff;">whoami</span> - About me<br>&nbsp;&nbsp;<span style="color:#00d2ff;">skills</span> - My tech stack<br>&nbsp;&nbsp;<span style="color:#00d2ff;">projects</span> - My projects<br>&nbsp;&nbsp;<span style="color:#00d2ff;">certs</span> - Certifications<br>&nbsp;&nbsp;<span style="color:#00d2ff;">contact</span> - Get in touch<br>&nbsp;&nbsp;<span style="color:#00d2ff;">clear</span> - Clear terminal`,whoami: () => `Jarajapu Gowtham — BCA Student at Aditya Degree College, Visakhapatnam.<br>MERN Stack Developer`,skills: () => `Languages: <span style="color:#00d2ff;">HTML5, CSS3, JavaScript, Python, Java</span><br>Stack: <span style="color:#00d2ff;">MERN</span><br>Tools: <span style="color:#00d2ff;">Git, GitHub, REST API</span>`,projects: () => `1. <span style="color:#00d2ff;">Sky Cast - Weather App</span><br>&nbsp;&nbsp;Live: sky-cast-gamma-steel.vercel.app<br><br>2. <span style="color:#00d2ff;">APSCHE Practice Portal</span><br>&nbsp;&nbsp;Live: apsche-practicemodel.vercel.app`,certs: () => `1. MERN Stack Internship - May 2026<br>2. AI & ML Research - ULearn, CU Denver<br>3. Python Essentials - Cisco<br>4. C Essentials 1 & 2 - Cisco<br>5. Aditya Tech Fusion Hackathon`,contact: () => `Email: <span style="color:#00d2ff;">Jarajapugowtham0851@gmail.com</span><br>GitHub: <span style="color:#00d2ff;">github.com/jarajapugowtham</span><br>LinkedIn: <span style="color:#00d2ff;">linkedin.com/in/jarajapu-gowtham-b304112ab</span>`,clear: () => { terminalOutput.innerHTML = ''; return null; },};
    if(terminalInput){terminalInput.addEventListener('keydown', (e) => {if (e.key === 'Enter') {const command = terminalInput.value.trim().toLowerCase();const output = terminalCommands[command]? terminalCommands[command]() : `Command not found: ${command}. Type 'help'`;if (output!== null) terminalOutput.innerHTML += `<p>${output}</p>`;terminalInput.value = '';terminalOutput.scrollTop = terminalOutput.scrollHeight;}});}
    const revealElements = document.querySelectorAll('.reveal');const observer = new IntersectionObserver((entries) => {entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('active'); });}, { threshold: 0.1 });revealElements.forEach(el => observer.observe(el));
    const form = document.getElementById('form');if (form) {form.addEventListener('submit', (e) => {e.preventDefault();const name = document.getElementById('name').value;const email = document.getElementById('email').value;const message = document.getElementById('message').value;const subject = encodeURIComponent(`Portfolio Contact from ${name}`);const body = encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\nMessage:\n${message}`);window.location.href = `mailto:Jarajapugowtham0851@gmail.com?subject=${subject}&body=${body}`;});}
    const rocketBtn = document.getElementById('rocket-easter-egg');const rocketCanvas = document.getElementById('rocket-canvas');if(rocketBtn && rocketCanvas){const ctx = rocketCanvas.getContext('2d');let particles = [];rocketBtn.addEventListener('click', () => {rocketCanvas.width = window.innerWidth; rocketCanvas.height = window.innerHeight;for(let i=0; i<100; i++) particles.push({x: window.innerWidth/2, y: window.innerHeight-50, vx: (Math.random()-0.5)*10, vy: -Math.random()*15-5, life: 100});animateRocket();});function animateRocket(){ctx.clearRect(0,0,rocketCanvas.width, rocketCanvas.height);particles.forEach((p, i) => {p.x += p.vx; p.y += p.vy; p.vy += 0.1; p.life--;ctx.fillStyle = `rgba(0,210,255,${p.life/100})`;ctx.beginPath(); ctx.arc(p.x, p.y, 3, 0, Math.PI*2); ctx.fill();if(p.life <= 0) particles.splice(i,1);});if(particles.length > 0) requestAnimationFrame(animateRocket);}}
});
